---
- name: "Download Agent Package"
  get_url:
    url: "http://{{ teamcity_agent_server_url }}:{{ teamcity_agent_server_port }}/update/buildAgent.zip"
    dest: /tmp
    validate_certs: no
    timeout: 60
  register: _teamcity_agent_package

- name: "Install Zip"
  apt:
    name: ['zip']
    state: present
    update_cache: yes

- name: "Create Agent Build dir"
  file:
    path: "{{ teamcity_agent_install_dir }}"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: "Check if bin existis"
  stat:
    path: "{{ teamcity_agent_install_dir }}/bin/agent.sh"
  register: _teamcity_agent_start_script

- name: "Unpack distribution"
  unarchive:
    src: "/tmp/buildAgent.zip"
    dest: "{{ teamcity_agent_install_dir }}"
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    remote_src: "yes"
  when: _teamcity_agent_package is changed or _teamcity_agent_start_script.stat.exists == False

- name: "Add TeamCity Agent service default config"
  template:
    src: "teamcity-agent.j2"
    dest: "/etc/default/teamcity-agent"
    mode: 0644

- name: "Put TeamCity Agent service file (sysv)"
  template:
    src: "teamcity-agent.conf.j2"
    dest: "/etc/init/teamcity-agent.conf"
    mode: 0644
  when: "ansible_service_mgr != 'systemd'"

- name: "Put TeamCity Agent service file (systemd)"
  template:
    src: "teamcity-agent.service.j2"
    dest: "/lib/systemd/system/teamcity-agent.service"
    #mode: 0644
  when: "ansible_service_mgr == 'systemd'"

- name: "Save agent auth token"
  shell: "grep authorizationToken {{ teamcity_agent_install_dir }}/conf/buildAgent.properties | sed 's/authorizationToken=//g'"
  changed_when: no
  register: _teamcity_agent_token

- name: "Create configuration directory"
  file:
    path: "{{ teamcity_agent_install_dir }}/conf"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: "Add TeamCity Agent configuration"
  template:
    src: "buildAgent.properties.j2"
    dest: "{{ teamcity_agent_install_dir }}/conf/buildAgent.properties"
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0644

- name: "Create log directory"
  file:
    path: "{{ teamcity_agent_install_dir }}/logs"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: "Ensure TeamCity Agent is running"
  service:
    name: teamcity-agent
    state: started
    enabled: yes
